#!/usr/bin/env bash
set -euo pipefail

: "${DB_APP_USER:?Debe definir DB_APP_USER}"
: "${DB_APP_PASSWORD:?Debe definir DB_APP_PASSWORD}"

psql -v ON_ERROR_STOP=1 <<SQL
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'DB_APP_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;', :'DB_APP_USER', :'DB_APP_PASSWORD');
  END IF;
END$$;
SQL