#!/bin/bash
#
# Align Designs - Server Provisioning Script
#
# Este script configura un servidor Ubuntu nuevo con:
# - SSH hardening (puerto 29, solo keys)
# - fail2ban (3 intentos = 24h ban)
# - UFW firewall
# - Docker & Docker Compose
# - Nginx
# - Certbot (SSL)
#
# Uso:
#   1. Copiar tu SSH key al servidor nuevo (puerto 22 inicial)
#   2. Copiar este script al servidor
#   3. Ejecutar: sudo bash provision-server.sh
#
# IMPORTANTE: Ejecutar como root en un servidor Ubuntu 22.04/24.04 limpio
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
SSH_PORT=29
FAIL2BAN_MAXRETRY=3
FAIL2BAN_BANTIME=86400  # 24 hours in seconds
TIMEZONE="America/Mexico_City"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Align Designs Server Provisioning${NC}"
echo -e "${GREEN}========================================${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Error: Please run as root (sudo bash provision-server.sh)${NC}"
  exit 1
fi

# Check Ubuntu version
if ! grep -q "Ubuntu" /etc/os-release; then
  echo -e "${RED}Error: This script is designed for Ubuntu${NC}"
  exit 1
fi

echo -e "${YELLOW}Starting server provisioning...${NC}"

# ============================================
# 1. System Update
# ============================================
echo -e "\n${GREEN}[1/8] Updating system packages...${NC}"
apt update && apt upgrade -y

# Set timezone
timedatectl set-timezone $TIMEZONE

# ============================================
# 2. Install Essential Packages
# ============================================
echo -e "\n${GREEN}[2/8] Installing essential packages...${NC}"
apt install -y \
  curl \
  wget \
  git \
  htop \
  unzip \
  software-properties-common \
  apt-transport-https \
  ca-certificates \
  gnupg \
  lsb-release

# ============================================
# 3. SSH Hardening
# ============================================
echo -e "\n${GREEN}[3/8] Configuring SSH hardening...${NC}"

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup

# Create hardened SSH config
cat > /etc/ssh/sshd_config << EOF
# Align Designs - Hardened SSH Config
# Generated by provision-server.sh

# Use non-standard port
Port $SSH_PORT

# Protocol
Include /etc/ssh/sshd_config.d/*.conf

# Authentication
PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
MaxAuthTries 3

# Security
X11Forwarding no
AllowAgentForwarding no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Connection settings
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30

# PAM
UsePAM yes

# Logging
SyslogFacility AUTH
LogLevel INFO

# SFTP
Subsystem sftp /usr/lib/openssh/sftp-server

# Environment
AcceptEnv LANG LC_*
PrintMotd no
EOF

# Stop socket service, change port, restart
echo -e "${YELLOW}Changing SSH port to $SSH_PORT...${NC}"
systemctl stop ssh.socket 2>/dev/null || true
systemctl stop sshd.socket 2>/dev/null || true
systemctl disable ssh.socket 2>/dev/null || true
systemctl disable sshd.socket 2>/dev/null || true

# Restart SSH service
systemctl restart ssh || systemctl restart sshd

echo -e "${GREEN}SSH configured on port $SSH_PORT${NC}"
echo -e "${YELLOW}IMPORTANT: Keep this session open and test new connection!${NC}"

# ============================================
# 4. Install & Configure fail2ban
# ============================================
echo -e "\n${GREEN}[4/8] Installing and configuring fail2ban...${NC}"
apt install -y fail2ban

# Create fail2ban jail config
cat > /etc/fail2ban/jail.local << EOF
# Align Designs - fail2ban Configuration
# 3 failed attempts = 24 hour ban

[DEFAULT]
bantime = $FAIL2BAN_BANTIME
findtime = 600
maxretry = $FAIL2BAN_MAXRETRY
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = $FAIL2BAN_MAXRETRY
bantime = $FAIL2BAN_BANTIME
EOF

# Restart fail2ban
systemctl enable fail2ban
systemctl restart fail2ban

echo -e "${GREEN}fail2ban configured: $FAIL2BAN_MAXRETRY attempts = 24h ban${NC}"

# ============================================
# 5. Configure UFW Firewall
# ============================================
echo -e "\n${GREEN}[5/8] Configuring UFW firewall...${NC}"
apt install -y ufw

# Reset UFW
ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH on custom port
ufw allow $SSH_PORT/tcp comment 'SSH'

# Allow HTTP/HTTPS
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'

# Allow internal Docker communication (optional)
# ufw allow from 172.16.0.0/12

# Enable UFW
ufw --force enable

echo -e "${GREEN}UFW configured and enabled${NC}"
ufw status verbose

# ============================================
# 6. Install Docker
# ============================================
echo -e "\n${GREEN}[6/8] Installing Docker...${NC}"

# Remove old versions
apt remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true

# Add Docker's official GPG key
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
apt update
apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Start Docker
systemctl enable docker
systemctl start docker

# Verify installation
docker --version
docker compose version

echo -e "${GREEN}Docker installed successfully${NC}"

# ============================================
# 7. Install & Configure Nginx
# ============================================
echo -e "\n${GREEN}[7/8] Installing Nginx...${NC}"
apt install -y nginx

# Start Nginx
systemctl enable nginx
systemctl start nginx

# Create directory for sites
mkdir -p /var/www/align-designs

echo -e "${GREEN}Nginx installed successfully${NC}"

# ============================================
# 8. Install Certbot for SSL
# ============================================
echo -e "\n${GREEN}[8/8] Installing Certbot for SSL...${NC}"
apt install -y certbot python3-certbot-nginx

echo -e "${GREEN}Certbot installed successfully${NC}"

# ============================================
# Create Docker network for web proxy
# ============================================
echo -e "\n${GREEN}Creating Docker web-proxy network...${NC}"
docker network create web-proxy 2>/dev/null || echo "Network web-proxy already exists"

# ============================================
# Final Summary
# ============================================
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Server Provisioning Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "SSH Port: ${YELLOW}$SSH_PORT${NC}"
echo -e "fail2ban: ${YELLOW}$FAIL2BAN_MAXRETRY attempts = 24h ban${NC}"
echo -e "UFW: ${YELLOW}Enabled (ports $SSH_PORT, 80, 443)${NC}"
echo -e "Docker: ${YELLOW}$(docker --version)${NC}"
echo -e "Nginx: ${YELLOW}$(nginx -v 2>&1)${NC}"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo "1. Test SSH connection on port $SSH_PORT from another terminal"
echo "2. Copy your SSH key if not already done:"
echo "   ssh-copy-id -p $SSH_PORT root@YOUR_SERVER_IP"
echo "3. Clone the repository to /var/www/align-designs"
echo "4. Configure .env.dev with your credentials"
echo "5. Run: docker compose -f docker-compose.dev.yml up -d"
echo ""
echo -e "${RED}WARNING: Do not close this session until you verify SSH works on port $SSH_PORT!${NC}"
